---
# Alright we're using the kubeadm init
# You can reset this with:
#  [root@kube-master centos]# kubeadm --help | grep reset
#    reset       Run this to revert any changes made to this host by 'kubeadm init' or 'kubeadm join'.

- name: create kubeadm config file
  block:
    - name: Install jq binary
      get_url:
        url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        dest: /usr/bin/jq

    - name: set jq binary permission
      file:
        path: /usr/bin/jq
        mode: 0755

    - name: check kubeadm version (major)
      shell: >
        kubeadm version -o json | jq -r .clientVersion.major
      register: kubeadm_version_major

    - name: check kubeadm version (minor)
      shell: >
        kubeadm version -o json | jq -r .clientVersion.minor | sed -e 's/\+//g'
      register: kubeadm_version_minor

    - name: determine kubeadm config API version
      set_fact:
        kubeadm_config_version: >-
          {%- if (kubeadm_version_major.stdout | int == 1 and kubeadm_version_minor.stdout | int >= 31) -%}
          v1beta4
          {%- else -%}
          v1beta3
          {%- endif -%}

    - name: display kubeadm version and config API version
      debug:
        msg: |
          Kubeadm version: {{ kubeadm_version_major.stdout }}.{{ kubeadm_version_minor.stdout }}
          Using kubeadm config API version: {{ kubeadm_config_version }}
          Container runtime: {{ container_runtime }}

    - name: create kubeadm config file (v1beta4 for k8s 1.31+)
      template:
        src: kubeadm.cfg.v1beta4.j2
        dest: /root/kubeadm.cfg
        mode: 0644
      when: kubeadm_config_version == "v1beta4"

    - name: create kubeadm config file (v1beta3 for k8s < 1.31)
      template:
        src: kubeadm.cfg.v1beta3.j2
        dest: /root/kubeadm.cfg
        mode: 0644
      when: kubeadm_config_version == "v1beta3"

- name: Default cri-o flags to empty
  set_fact:
    arg_crio: ""

- name: Set cri-o flags for v1beta3 config
  set_fact:
    arg_crio: "--ignore-preflight-errors=all"
  when: 
    - kubeadm_config_version == "v1beta3"
    - container_runtime in ["crio", "crio_k8s", "crio_rpm", "crio_file", "crio_crun"]

- name: Default k8s version to empty
  set_fact:
    k8s_version: ""

- name: set upload-certs in kubeadm option
  set_fact:
    k8s_upload_certs: ""

- name: set upload-certs in kubeadm option
  set_fact:
    k8s_upload_certs: "--upload-certs"
  when: groups.master_slave is defined and groups.master_slave|length > 0

- name: Run kubeadm init
  shell: >
    kubeadm init {{ k8s_version }} {{ arg_crio }} {{ k8s_upload_certs }} {{ kubeadm_flags | default("") }} --config=/root/kubeadm.cfg > /var/log/kubeadm.init.log
  args:
    creates: /etc/.kubeadm-complete

- name: Mark init complete
  file:
    path: /etc/.kubeadm-complete
    state: directory
    mode: 0644

- name: Get join command # noqa 301
  shell: >
    kubeadm token create --print-join-command
  register: kubeadm_join_output

- name: Set fact with join command
  set_fact:
    kubeadm_join_command: "{{ kubeadm_join_output.stdout }}"

- name: Get certificate-key
  shell: >
          set -o pipefail && kubeadm init phase upload-certs --upload-certs -v 0 2> /dev/null | tail -n 1
  register: kubeadm_cert_key_output
  when: groups.master_slave is defined and groups.master_slave|length > 0

- name: Set fact with certificate-key
  set_fact:
    kubeadm_cert_key: "{{ kubeadm_cert_key_output.stdout }}"
  when: groups.master_slave is defined and groups.master_slave|length > 0
