- name: Check if helmfile is already installed
  stat:
    path: /usr/local/bin/helmfile
  register: helmfile_bin

- name: Download helmfile archive
  get_url:
    url: "https://github.com/helmfile/helmfile/releases/download/v{{ helmfile_version }}/helmfile_{{ helmfile_version }}_{{ ansible_system | lower }}_{{ arch_map[ansible_architecture] }}.tar.gz"
    dest: /tmp/helmfile_{{ helmfile_version }}_{{ ansible_system | lower }}_{{ arch_map[ansible_architecture] }}.tar.gz
    mode: '0644'
  when: not helmfile_bin.stat.exists

- name: Extract helmfile binary
  unarchive:
    src: /tmp/helmfile_{{ helmfile_version }}_{{ ansible_system | lower }}_{{ arch_map[ansible_architecture] }}.tar.gz
    dest: /tmp/
    remote_src: yes
    creates: /tmp/helmfile
  when: not helmfile_bin.stat.exists

- name: Move helmfile binary to /usr/local/bin
  copy:
    src: /tmp/helmfile
    dest: /usr/local/bin/helmfile
    mode: '0755'
    remote_src: yes
  when: not helmfile_bin.stat.exists

- name: Clean up extracted files
  file:
    path: "/tmp/helmfile_{{ helmfile_version }}_{{ ansible_system | lower }}_{{ arch_map[ansible_architecture] }}.tar.gz"
    state: absent
  when: not helmfile_bin.stat.exists

- name: Clean up helmfile binary from /tmp
  file:
    path: "/tmp/helmfile"
    state: absent
  when: not helmfile_bin.stat.exists